# Generated by Django 5.2 on 2025-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='center_logo',
            field=models.ImageField(blank=True, null=True, upload_to='service_center_logo/'),
        ),
    ]
