# Generated by Django 5.2 on 2025-04-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_remove_servicebooking_id_remove_vehiclebooking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclebooking',
            old_name='service_id',
            new_name='booking_id',
        ),
    ]
